### ISSUE TITLE
Display upstream and downstream runs live on the run page

### ISSUE THREAD

**Issue by LudovicoRighi** [apsis-scheduler/apsis#356]
The idea is to enhance the run page UI to display upstream and downstream dependency runs live, similar to Tidal's approach. 

This feature has been requested by many people as it would significantly improve our ops processes.

cc @alexhsamuel @gusostow

**Comment by alexhsamuel** [comment]
Need to fix #366, or else this will show incorrect results for completed runs.

**Comment by gusostow** [comment]
Small issue - on first page load, it displays no dependencies/dependents until it gets populated. Similar to https://github.com/alexhsamuel/apsis/issues/384.

Also, worth mentioning that loading this data is a bit slow, ~5-10s, in case there's any easy improvements there.

**Comment by alexhsamuel** [comment]
The best we can do at the moment is to hide the dependencies entirely until the run loading is complete.  I've already optimized the run loading pretty intensely, and I don't know of any easy improvements in the implementation.  Reducing the run retention in your config would reduce the load time, as it should scale pretty much linearly with the number of runs Apsis tracks.

P.S. Please open new issues instead of appending to existing, closed ones.
