### ISSUE TITLE
Accept jobs with `.yml` extension?  

### ISSUE THREAD

**Issue by gusostow** [apsis-scheduler/apsis#400]
Continuing discussion from https://github.com/alexhsamuel/apsis/issues/336#issuecomment-2468723003.

`.yml` might not be the official recommendation, but it's still a common choice. For example, it's the extension for Github Actions starter workflows https://github.com/actions/starter-workflows/tree/main/ci.

**Comment by alexhsamuel** [comment]
How do you feel a git commit hook, which I proposed in that issue?

**Comment by gusostow** [comment]
Setting up tooling to reject bad extensions feels like a lot of work and user friction compared to accepting the common, mostly-correct alternative. I guess I'm not understanding your distaste for it.

**Comment by alexhsamuel** [comment]
Because this breaks the one-to-one mapping between jobs dir paths and job IDs.

For example, we'll need to choose and implement a policy for a case where there's both `job.yml` and `job.yaml`.  We'll have to store the path (or at least the suffix) as well as the job ID, if we want to built tools that manipulate the jobs files programatically.  And that's just off the top of my head.

**Comment by gusostow** [comment]
That make sense. I thought you were just objecting for aesthetic reasons. Other options look more favorable now compared to making those changes.
